server:
  port: 8088
  tomcat:
    uri-encoding: UTF-8

spring:
  application:
    name: @pom.artifactId@
  profiles:
    active: @profileActive@
  datasource:
    url: jdbc:mysql://luxiaotao.top:3306/cool_blog?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false&verifyServerCertificate=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: xltys1995

mybatis:
  mapperLocations: classpath*:mapper/*Mapper.xml
  configuration:
    mapUnderscoreToCamelCase: true
    cache-enabled: true
